### ISSUE TITLE
Twisting occuring

### ISSUE THREAD

**Issue by jamalknight** [zju3dv/EasyMocap#110]
hi there

This model works well, but I have found that there is some 'twisting' that happens when the mesh twists 360 degrees. I suspect that more cameras solves this (in the example attached I'm using 4 cameras) 

Are there any known solutions for this?

Thanks

https://user-images.githubusercontent.com/38970401/145704581-94de841f-4232-44c1-8b95-f3fe9d7351aa.mp4

**Comment by JACKYLUO1991** [comment]
@jamalknight I am facing the same problem, maybe changing the parameters will solve it? Have you found a good way to do it?

**Comment by jamalknight** [comment]
@JACKYLUO1991  I think it has to do with the number of camera sources. I tested using 2, and 3 sources and the twisting was much worse. Adding cameras reduces it, so it seems.
An option is to fix the twisting once the SMPL mesh is created because the twisting keyframes can be deleted (in Blender for example) on the bones/joints.

**Comment by JACKYLUO1991** [comment]
@jamalknight Thanks for your reply, we are aiming to drive Avatar in real time and can't fix it ourselves, I am trying to change the parameters etc, if there is a better way, please advise.

**Comment by chingswy** [comment]
Hello, this is a bug in v0.1 and will be fixed in v0.2. Specifically, it is because the wrong smooth of the rotation.

**Comment by jamalknight** [comment]
Hello, do you have an ETA on the update?

**Comment by chingswy** [comment]
I will release the new designed code this month.

**Comment by DiverFar-Inc** [comment]
Hey @chingswy ! Any news for fixing twisting problem? V.02 release?

**Comment by DiverFar-Inc** [comment]
Thanks!









ср, 20 июл. 2022 г. в 15:19, gqbay ***@***.***>:

**Comment by chingswy** [comment]
Fixed.

**Comment by ferhatsb** [comment]
I still experience twisting at master branch and I don't see any V0.2, what I miss ?
